"""create mail schema

Revision ID: 986096a748a4
Revises: 
Create Date: 2026-05-13 13:10:42.510248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '986096a748a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS mail'))
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mail_from', sa.Text(), nullable=False),
    sa.Column('rcpt_tos', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('raw_message', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mail'
    )
    op.create_table('delivery_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('mx_host', sa.Text(), nullable=True),
    sa.Column('smtp_code', sa.Integer(), nullable=True),
    sa.Column('smtp_response', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['mail.outbox.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mail'
    )
    op.create_index(op.f('ix_mail_delivery_attempts_email_id'), 'delivery_attempts', ['email_id'], unique=False, schema='mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_delivery_attempts_email_id'), table_name='delivery_attempts', schema='mail')
    op.drop_table('delivery_attempts', schema='mail')
    op.drop_table('outbox', schema='mail')
    op.execute(sa.text('DROP SCHEMA IF EXISTS mail'))
    # ### end Alembic commands ###
